from pathlib import Path
import torch
ROOT_DIR = Path(__file__).parent
OUTPUT_FOLDER_NAME = "__output"
DATALOADER = "data_loader"
BATCH_SIZE = "batch_size"
TRAIN, VALIDATION, TEST = "train", "validation", "test"
ID = "id"
NAME = "name"
NB_EPOCHS = "nb_epochs"
ARCHITECTURE = "architecture"
MODEL = "model"
NAME = "name"
N_PARAMS = "n_params"
OPTIMIZER = "optimizer"
LR = "lr"
PARAMS = "parameters"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SCHEDULER_CONFIGURATION = "scheduler_configuration"
SCHEDULER = "scheduler"
REDUCELRONPLATEAU = "ReduceLROnPlateau"
ACCURACY = "accuracy"
AUGMENTATION_LIST = "augmentation_list"
AUGMENTATION_H_ROLL_WRAPPED = "h_roll"
AUGMENTATION_AWGN = "awgn"
AUGMENTATION_BIAS = "bias"
AUGMENTATION_COEFF = "coeff"
AUGMENTATION_FLIP = "flip"
